"""Generate firmware/fonts/clock_font.h from a TTF font.

Each glyph is rasterized at GLYPH_W × GLYPH_H, packed MSB-first row-major,
and emitted as a PROGMEM byte array. The result is a header drop-in that
compiles into the ESP32 firmware.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

GLYPH_W = 56
GLYPH_H = 100
DIGIT_FONT_SIZE = 110  # tuned so digits fill ~85% of GLYPH_H

CHARS = "0123456789:"

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
FONT_PATH = PROJECT_ROOT / "assets" / "fonts" / "Heebo-Regular.ttf"
OUT_PATH = Path(__file__).resolve().parent / "clock_font.h"


def rasterize_glyph(ch: str, font: ImageFont.FreeTypeFont) -> bytes:
    """Draw a single character centered in a GLYPH_W × GLYPH_H 1-bit canvas.

    Returns the packed bytes (row-major, MSB-first, padded to whole byte).
    """
    img = Image.new("L", (GLYPH_W, GLYPH_H), 255)
    draw = ImageDraw.Draw(img)
    bbox = font.getbbox(ch)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    x = (GLYPH_W - text_w) // 2 - bbox[0]
    y = (GLYPH_H - text_h) // 2 - bbox[1]
    draw.text((x, y), ch, font=font, fill=0)
    bw = img.convert("1", dither=Image.Dither.NONE)

    bytes_per_row = (GLYPH_W + 7) // 8
    out = bytearray(bytes_per_row * GLYPH_H)
    px = bw.load()
    for row in range(GLYPH_H):
        for col in range(GLYPH_W):
            if px[col, row] == 0:  # black pixel → set bit
                out[row * bytes_per_row + (col >> 3)] |= 1 << (7 - (col & 7))
    return bytes(out)


def emit_array(name: str, data: bytes) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"  {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    font = ImageFont.truetype(str(FONT_PATH), DIGIT_FONT_SIZE)

    glyphs = {ch: rasterize_glyph(ch, font) for ch in CHARS}

    bytes_per_row = (GLYPH_W + 7) // 8
    glyph_size = bytes_per_row * GLYPH_H

    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "// Auto-generated by firmware/fonts/generate_clock_font.py\n"
            "// Do not edit by hand — re-run the generator to update.\n\n"
            "#pragma once\n"
            "#include <stdint.h>\n"
            "#include <pgmspace.h>\n\n"
            f"#define CLOCK_GLYPH_W {GLYPH_W}\n"
            f"#define CLOCK_GLYPH_H {GLYPH_H}\n"
            f"#define CLOCK_GLYPH_ROW_BYTES {bytes_per_row}\n"
            f"#define CLOCK_GLYPH_BYTES {glyph_size}\n\n"
        )

        for ch in CHARS:
            ident = "DIGIT_" + (ch if ch != ":" else "COLON")
            f.write(emit_array(ident, glyphs[ch]) + "\n\n")

        # Lookup table mapping ASCII '0'..'9' / ':' to the right glyph pointer.
        f.write("inline const uint8_t* clockGlyphFor(char c) {\n")
        f.write("  switch (c) {\n")
        for ch in CHARS:
            ident = "DIGIT_" + (ch if ch != ":" else "COLON")
            f.write(f"    case '{ch}': return {ident};\n")
        f.write("    default: return nullptr;\n")
        f.write("  }\n")
        f.write("}\n")

    print(f"wrote {OUT_PATH}  ({len(CHARS)} glyphs, {glyph_size} bytes each)")


if __name__ == "__main__":
    main()
